name: Patreon to Discord Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes — adjust as needed
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Restore post ID cache
        uses: actions/cache@v4
        with:
          path: recent_posts.json
          key: patreon-cache-file

      - name: Install dependencies
        run: pip install requests

      - name: Run femmebot scraper
        env:
          PATREON_ACCESS_TOKEN: ${{ secrets.PATREON_ACCESS_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python femmebot_scraper.py
